### ISSUE TITLE
Gotta #include <memory> and <functional>

### ISSUE THREAD

**Issue by dllu** [bexcite/apolloscape-sfm#2]
The code presently fails to compile with `g++ 8.3.0` because it uses, for exmaple, `std::shared_ptr` from `#include <memory>` and `std::function` from `#include <functional>` but does not include either of the two.

For example, here is the first error message:

```
In file included from /home/dllu/proj/apolloscape-sfm/src/shader.cpp:9:
/home/dllu/proj/apolloscape-sfm/include/cv_gl/shader.h:49:55: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
 std::ostream& operator<<(std::ostream &os, const std::shared_ptr<Shader>& shader);
                                                       ^~~~~~~~~~
/home/dllu/proj/apolloscape-sfm/include/cv_gl/shader.h:49:50: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
```

It seems we need to add `#include <memory>` at the top of `shader.h` and `#include <functional>` at the top of `gl_window.h`.

**Comment by bexcite** [comment]
Thanks for catching this, my "magic machine" still works:) I've added this two deps but haven't tested it for g++ 8.3.0. Definitely, there are some hidden dependencies problem that didn't pop up on my Mac OS Clang setup. Hope you've been able to compile it.
